# Generated by Django 5.0.10 on 2026-04-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_quantity_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Article panier', 'verbose_name_plural': 'Articles panier'},
        ),
    ]
