# Generated by Django 5.0.10 on 2026-04-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banniere', 'verbose_name_plural': 'Bannieres'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie', 'verbose_name_plural': 'Categories'},
        ),
    ]
