# Generated by Django 5.0.10 on 2026-04-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_announcement_options_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('truck', 'Livraison'), ('shield', 'Garantie'), ('headphones', 'Support'), ('credit-card', 'Paiement'), ('gift', 'Cadeau'), ('star', 'Étoile')], default='truck', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fonctionnalité',
                'verbose_name_plural': 'Fonctionnalités',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Nouveautés 2024', help_text='Texte du badge (ex: Nouveautés 2024)', max_length=100)),
                ('title', models.CharField(default='Découvrez les meilleurs smartphones du marché', max_length=255)),
                ('title_highlight', models.CharField(blank=True, default='smartphones', help_text='Mot mis en rouge dans le titre', max_length=100)),
                ('description', models.TextField(default='iPhone 15, Samsung Galaxy S24, et bien plus encore. Livraison gratuite et garantie 12 mois.')),
                ('button1_text', models.CharField(default='Explorer les produits', max_length=100)),
                ('button1_link', models.CharField(default='/produit', max_length=200)),
                ('button2_text', models.CharField(default='Voir les promos', max_length=100)),
                ('button2_link', models.CharField(default='/produit?promo=true', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Hero',
                'verbose_name_plural': 'Sections Hero',
            },
        ),
        migrations.CreateModel(
            name='SolutionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(default='smartphone', help_text="Nom de l'icône (smartphone, headphones, monitor, flame)", max_length=50)),
                ('link', models.CharField(default='/produit', max_length=200)),
                ('bg_gradient', models.CharField(default='from-gray-800 to-gray-900', help_text='Classes Tailwind du dégradé', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carte Solution',
                'verbose_name_plural': 'Cartes Solutions',
                'ordering': ['order'],
            },
        ),
    ]
