# Generated by Django 5.0.10 on 2026-04-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Liste de souhaits', 'verbose_name_plural': 'Listes de souhaits'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-added_at'], 'verbose_name': 'Article favori', 'verbose_name_plural': 'Articles favoris'},
        ),
    ]
