# Generated by Django 5.0.10 on 2025-11-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='production',
        ),
    ]
