# Generated by Django 5.0.10 on 2025-11-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='battery_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Capacité batterie en mAh', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Neuf'), ('refurbished', 'Reconditionné'), ('used', 'Occasion')], default='new', max_length=20, verbose_name='État'),
        ),
        migrations.AddField(
            model_name='product',
            name='dual_sim',
            field=models.BooleanField(default=False, verbose_name='Double SIM'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_camera',
            field=models.CharField(blank=True, help_text='Ex: 32MP', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_camera',
            field=models.CharField(blank=True, help_text='Ex: 108MP + 12MP + 5MP', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modèle'),
        ),
        migrations.AddField(
            model_name='product',
            name='network',
            field=models.CharField(blank=True, choices=[('2g', '2G'), ('3g', '3G'), ('4g', '4G'), ('5g', '5G')], max_length=10, verbose_name='Réseau'),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('other', 'Autre')], max_length=20, verbose_name="Système d'exploitation"),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.PositiveIntegerField(blank=True, help_text='RAM en Go', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taille écran en pouces', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.PositiveIntegerField(blank=True, help_text='Stockage en Go', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='produits.brand'),
        ),
    ]
