# Generated by Django 5.0.10 on 2026-04-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_brand_alter_product_options_product_battery_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marque', 'verbose_name_plural': 'Marques'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
    ]
